logging:
  level:
    root: info
    com.kcd.recruit: debug

server:
  port: 8080

spring:
  profiles:
    active: local
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: crawler.vhost
    username: guest
    password: guest
    listener:
      simple:
        prefetch: 1
        auto-startup: false